### ISSUE TITLE
fs2-data streaming xml parser?

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s-scala-xml#4]
Just a random idea worth exploring.

https://github.com/satabin/fs2-data

**Comment by rossabaker** [comment]
Ooh, that could be neat.  There is an incremental one called Aalto that I had my eye on for a while, but never got around to integrating.

This would of course introduce another dependency of unknown stability.

**Comment by armanbilge** [comment]
I'm partial to fs2-data since it cross-builds for Scala.js 😉 two birds with one stone https://github.com/http4s/http4s-scala-xml/issues/3

**Comment by armanbilge** [comment]
Here's another streaming xml parser.
https://github.com/ScalaWilliam/xs4s

**Comment by rossabaker** [comment]
Pros and cons: fs2-data has its own XML parser.  xs4s uses the battle-tested Java parser, but requires a `java.io.InputStream`.

**Comment by armanbilge** [comment]
The latest release of fs2-data-xml just added support for directly building scala-xml trees. So this is probably extremely easy to implement now.

https://github.com/satabin/fs2-data/releases/tag/v1.4.0

**Comment by rossabaker** [comment]
I did an [aalto spike](https://github.com/rossabaker/fs2-data/commit/23a01c6ec1e0410ba2cf31d06965e52ade8b7e19).  It's VERY fast, but incomplete, and I think I'm cheating badly with mutable state.

**Comment by armanbilge** [comment]
https://github.com/http4s/http4s-fs2-data
