### ISSUE TITLE
Release for 1.0.0-M36

### ISSUE THREAD

**Issue by reidrac** [http4s/http4s-scala-xml#71]
I'm trying to upgrade http4s to 1.0.0-M36 and I have a dependency on http4s-scala-xml, but that version is not available.

> sbt.librarymanagement.ResolveException: Error downloading org.http4s:http4s-scala-xml_3:1.0.0-M36

Any plans to release it?

Thank you!

**Comment by mlopes** [comment]
If I understand correctly the code is merged in `master`, the only thing missing is to create the actual release and make the artefacts available in maven, right?

**Comment by armanbilge** [comment]
@reidrac @mlopes is there a reason you folks are using http4s 1.0 milestones? It is an unstable development series, and I highly recommend you stick to the 0.23.x series.

Unfortunately we obviously don't have enough maintainers to keep up with all the latest milestones on integration repos such as this one.

**Comment by reidrac** [comment]
That's a fair question. As I understand it any fixes are backported from the 1.0 milestones to the 0.23.x series, so it should be fine.

I'll see what we can do. Thanks for your help!
