### ISSUE TITLE
Version conflict with  1.0.0-M38

### ISSUE THREAD

**Issue by javierg1975** [http4s/http4s-scala-xml#78]
Just tried upgrading to  1.0.0-M38 and get this error message

```
found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.http4s:http4s-core_3:1.0.0-M38 (early-semver) is selected over 0.23.17
[error] 	    +- org.http4s:http4s-client_3:1.0.0-M38               (depends on 1.0.0-M38)
[error] 	    +- org.http4s:http4s-server_3:1.0.0-M38               (depends on 1.0.0-M38)
[error] 	    +- org.http4s:http4s-dsl_3:1.0.0-M38                  (depends on 1.0.0-M38)
[error] 	    +- org.http4s:http4s-ember-core_3:1.0.0-M38           (depends on 1.0.0-M38)
[error] 	    +- org.http4s:http4s-scala-xml_3:1.0.0-M38            (depends on 0.23.17)
```

Double-checked and 1.0.0-M35 works fine. In both cases the version # is the same for the xml module and other http4s dependencies.

**Comment by rossabaker** [comment]
This is [my mistake](https://github.com/http4s/http4s-scala-xml/blob/v1.0.0-M38/build.sbt#L15).  We've tried to keep the version numbers the same across milestones, so I'll have to give the next one a weird version number.

**Comment by rossabaker** [comment]
Looks like I tagged the release from the wrong branch. 🤦

I just cut `1.0.0-M38.1`.  It should be on Maven Central in less than an hour, hopefully much less.  Let me know if that helps.

**Comment by javierg1975** [comment]
Works now. Thanks for the quick fix!
